version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - chatbot-network

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=cnj-chatbot
      - JITSI_DOMAIN=localhost:8443
      - JITSI_API_KEY=dev_key
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - jitsi
      - redis
    networks:
      - chatbot-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - chatbot-network

  jitsi:
    image: jitsi/web:web-1.0.8588-1
    ports:
      - "8443:443"
      - "10000:10000/udp"
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - ENABLE_LETSENCRYPT=0
      - ENABLE_TRANSCRIPTION=0
      - ENABLE_RECORDING=0
      - PUBLIC_URL=https://localhost:8443
    volumes:
      - jitsi_config:/config:Z
      - jitsi_prosody:/prosody/config:Z
      - jitsi_jvb:/jvb:Z
      - jitsi_jicofo:/jicofo:Z
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge

volumes:
  mongodb_data:
  jitsi_config:
  jitsi_prosody:
  jitsi_jvb:
  jitsi_jicofo: 